#!/bin/bash

# Firebase Setup Helper Script
# This script guides you through manually configuring Firebase

set -e

FRONTEND_DIR="$HOME/Downloads/Sydney/frontend"
BACKEND_DIR="$HOME/Downloads/Sydney/sydney-backend"

echo "🔥 Firebase Setup Helper for Sydney"
echo "======================================"
echo ""

# Check if files exist
if [ ! -f "$FRONTEND_DIR/lib/firebase_options.dart" ]; then
    echo "❌ firebase_options.dart not found!"
    exit 1
fi

echo "📋 Step-by-step Firebase Configuration"
echo ""
echo "First, let's set up your Firebase project..."
echo ""
echo "1. Go to: https://console.firebase.google.com"
echo "2. Create a new project or select existing one"
echo ""
read -p "Press ENTER when you have your Firebase Console open..."

echo ""
echo "3. Click the Android icon (</>) to add an Android app"
echo "4. Android package name: com.example.sydney"
echo "5. Click 'Register app'"
echo "6. Click 'Download google-services.json'"
echo ""
read -p "Press ENTER after you've downloaded google-services.json..."

# Check for downloaded google-services.json
echo ""
echo "Looking for google-services.json in ~/Downloads..."
if [ -f "$HOME/Downloads/google-services.json" ]; then
    echo "✅ Found google-services.json!"
    echo "Moving to $FRONTEND_DIR/android/app/"
    cp "$HOME/Downloads/google-services.json" "$FRONTEND_DIR/android/app/google-services.json"
    echo "✅ google-services.json copied successfully!"
else
    echo "⚠️  google-services.json not found in ~/Downloads"
    echo "Please manually copy it to: $FRONTEND_DIR/android/app/google-services.json"
    echo ""
    read -p "Press ENTER after you've copied the file..."
fi

echo ""
echo "📝 Now let's get your Firebase configuration values..."
echo ""
echo "In Firebase Console:"
echo "  → Click Project Settings (gear icon)"
echo "  → Scroll to 'Your apps'"
echo "  → Click on your Android app"
echo ""

read -p "Enter your API Key: " API_KEY
read -p "Enter your App ID: " APP_ID
read -p "Enter your Messaging Sender ID: " SENDER_ID
read -p "Enter your Project ID: " PROJECT_ID

echo ""
echo "✍️  Updating firebase_options.dart..."

# Update firebase_options.dart
cat > "$FRONTEND_DIR/lib/firebase_options.dart" <<EOF
// File generated by FlutterFire setup script
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '$API_KEY',
    appId: '$APP_ID',
    messagingSenderId: '$SENDER_ID',
    projectId: '$PROJECT_ID',
    storageBucket: '$PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '$API_KEY',
    appId: '$APP_ID',
    messagingSenderId: '$SENDER_ID',
    projectId: '$PROJECT_ID',
    storageBucket: '$PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.sydney',
  );
}
EOF

echo "✅ firebase_options.dart updated!"

echo ""
echo "🔐 Now let's set up the backend service account..."
echo ""
echo "In Firebase Console:"
echo "  → Project Settings → Service accounts tab"
echo "  → Click 'Generate new private key'"
echo "  → Click 'Generate key' (downloads JSON file)"
echo ""
read -p "Press ENTER after downloading the service account JSON..."

# Find the most recent firebase-adminsdk JSON file
SERVICE_ACCOUNT_FILE=$(ls -t "$HOME/Downloads/"*firebase-adminsdk*.json 2>/dev/null | head -1)

if [ -n "$SERVICE_ACCOUNT_FILE" ]; then
    echo "✅ Found service account file: $SERVICE_ACCOUNT_FILE"
    echo "Minifying JSON..."
    
    # Minify JSON using Python (more reliable than jq)
    if command -v python3 &> /dev/null; then
        MINIFIED=$(python3 -c "import json; print(json.dumps(json.load(open('$SERVICE_ACCOUNT_FILE')), separators=(',',':')))")
        
        # Check if .env exists
        if [ ! -f "$BACKEND_DIR/.env" ]; then
            echo "❌ $BACKEND_DIR/.env not found!"
            echo "Please create it first by copying .env.example"
            exit 1
        fi
        
        # Check if FIREBASE_SERVICE_ACCOUNT already exists
        if grep -q "^FIREBASE_SERVICE_ACCOUNT=" "$BACKEND_DIR/.env"; then
            echo "⚠️  FIREBASE_SERVICE_ACCOUNT already exists in .env"
            read -p "Replace it? (y/n): " REPLACE
            if [ "$REPLACE" = "y" ]; then
                # Remove old line and add new one
                grep -v "^FIREBASE_SERVICE_ACCOUNT=" "$BACKEND_DIR/.env" > "$BACKEND_DIR/.env.tmp"
                echo "FIREBASE_SERVICE_ACCOUNT='$MINIFIED'" >> "$BACKEND_DIR/.env.tmp"
                mv "$BACKEND_DIR/.env.tmp" "$BACKEND_DIR/.env"
                echo "✅ Updated FIREBASE_SERVICE_ACCOUNT in .env"
            fi
        else
            echo "FIREBASE_SERVICE_ACCOUNT='$MINIFIED'" >> "$BACKEND_DIR/.env"
            echo "✅ Added FIREBASE_SERVICE_ACCOUNT to .env"
        fi
    else
        echo "❌ Python3 not found. Please manually add service account to .env"
        echo "Contents saved to: /tmp/firebase_service_account.txt"
        cat "$SERVICE_ACCOUNT_FILE" > /tmp/firebase_service_account.txt
    fi
else
    echo "⚠️  Service account JSON not found in ~/Downloads"
    echo "Please manually add it to $BACKEND_DIR/.env:"
    echo "FIREBASE_SERVICE_ACCOUNT='...minified JSON...'"
fi

echo ""
echo "🗄️  Running database migration..."
cd "$BACKEND_DIR"
npm run migrate

echo ""
echo "✅ Firebase setup complete!"
echo ""
echo "🧪 To test:"
echo ""
echo "Terminal 1: cd $BACKEND_DIR && npm run dev:api"
echo "Terminal 2: cd $BACKEND_DIR && npm run dev:worker"
echo "Terminal 3: cd $FRONTEND_DIR && flutter run"
echo ""
echo "Then create an agent and tap 'Run now' to test push notifications!"
echo ""
